### PR TITLE
Minor refactoring and bug fixing

### PR DESCRIPTION
**Pull request by evgTSV**
Bug fixed (Issue #194) and improved code a bit

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Something's wrong. Here's now the main game window looks for me now :(

image

**Review by ForNeVeR — CHANGES_REQUESTED** [review]
I see what you are trying to do, but for some reason it breaks the previous rendering mode on HiDPI. Let's do something :)

I can help if you need.

**Comment by evgTSV** [comment]
I reproduced the problem and fixed it. The camera is configured with `RenderTargetSize` equal to size of the scene

**Review by ForNeVeR — APPROVED** [review]
Thanks!

**Pull request merged**
