### PR TITLE
Add "game over" window

### PR DESCRIPTION
**Pull request by sotiredofyours**
Part of #32.

### CODE REVIEW

**Comment by sotiredofyours** [comment]
@ForNeVeR In the process of implementation, I had two difficulties:
1. I didn't find the original submarine sprite from this window. I temporarily put a bonus life sprite. Is it okay or not?
2. In the original version of the game, by pressing the minimize button, we have several options: move and close. Will we be adding these features too?
image

**Comment by ForNeVeR** [comment]
> I didn't find the original submarine sprite from this window

I believe that's the game's executable icon. We don't seem to have it extracted, yet, and I'm not sure we'll want to bother. We'll have our own icon for the game executable, anyway (because we cannot embed the original content into our exe).

I propose let's leave the sprite for now and see if it's better.

In this project, we want to have 100% of the original game content and experience, but not necessarily 100% of the original UI, especially if we can improve some bits of it.

> In the original version of the game, by pressing the minimize button, we have several options: move and close. Will we be adding these features too?

Nah, don't bother. These are parts of the original Windows 3.1 window decoration, and serve no good purpose in the game window.,

**Comment by ForNeVeR** [comment]
Just to clarify: I have no _vision_ of how the window decorations should be implemented, so this is up to your imagination. If you want to reproduce the original Win3.1 border style, that's fine. If you want to do something simpler, that's fine as well.

**Comment by ForNeVeR** [comment]
JFYI, I don't believe we need a "Window System" here.

Once again, you can implement it if you wish, and it would be useful! (Including in other scenes.) But if you don't want to do that, then a basic implementation with a full-screen game-over screen would be fine for now.

The one you did looks great, though, and works really well as an homage to the old days of Windows.

One detail that may make the implementation easier is that we never ever want several floating windows to be on the screen.

Does that help? Do you need any advice on the overall architecture of the current solution? Or maybe you prefer me to merge this as-is already?

**Comment by sotiredofyours** [comment]
Thank you for the detailed answer. In that case, I think I'll stop there for now. I have some ideas on how to do it better in the future.

If you have no objections about the code style, let's merge it.

The next step in #32 is to make a window that asks for the player's name.

**Review by ForNeVeR — APPROVED** [review]
Thanks!

**Pull request merged**
