### PR TITLE
Disclaimer scene: migrate to the new scaling approach

### LINKED ISSUE #145: Disclaimer scene: migrate to the new scaling approach
Currently, our default disclaimer scene seems to have problems rendering the text in the default window size on my PC.

We should make it fit and use the camera/zoom approach, to make sure the text always will properly fit in screen if it fit once.

See `// TODO[#145]` in the code.

### PR DESCRIPTION
**Pull request by Fantoom**
closes #145

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Something's still wrong even in a branch with this PR, could you please take a look?
image

**Comment by ForNeVeR** [comment]
Also, the buttons don't seem to be working properly after this change: they are only clickable in their original position, not the actual position after resize.

In these images, I've highlighted the button active region before and after the game window resize.

image

image

**Comment by Fantoom** [comment]
They should fix some problems, but text is still not completely fixed

**Comment by ForNeVeR** [comment]
The buttons are fixed, the text is still bad. I'll have to investigate myself.

**Comment by Fantoom** [comment]
I found this [sample](https://www.raylib.com/examples/text/loader.html?name=text_rectangle_bounds). I think we can use it for that. Or we can manually edit the text file and add line breaks

**Comment by ForNeVeR** [comment]
it is already manually edited with manually-added line breaks :)

**Review by ForNeVeR — APPROVED** [review]
Thanks!

**Pull request merged**
