### PR TITLE
Add default screen size

### LINKED ISSUE #139: Screen width and height config
I think that we need a way to set screen width and height. We can do it as command line argument (--width and --height)

### PR DESCRIPTION
**Pull request by Fantoom**
Should close #139

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Does this works for you? For me, any of the following calls yield `0`:
- `Raylib_CsLo.Raylib.GetCurrentMonitor()`
- `Raylib_CsLo.Raylib.GetMonitorWidth 0`
- `Raylib_CsLo.Raylib.GetMonitorCount()` (wat?!)

**Comment by ForNeVeR** [comment]
Accessing any of those requires a call to `InitWindow`, apparently 😓

**Comment by Fantoom** [comment]
Ah, I have forgot about it, what solution do you suggest?

**Comment by ForNeVeR** [comment]
Ok, after a small discussion, I'll finish this work.

**Review by ForNeVeR — APPROVED** [review]
Thanks!

**Pull request merged**
